name: Tag Environments

on:
  pull_request:
    types:
      - labeled
    branches: 
      - ci-alpha

jobs:

  tag_env:
    runs-on: ubuntu-latest
    steps:

    - name: Check out GitHub Repo
      if: github.event.pull_request.merged == false
      uses: actions/checkout@v2
      with:
        ref: ${{ github.event.pull_request.head.sha }}


    - name: Set App Version and Name Vars
      if: github.event.pull_request.merged == false
      run: |
        echo ::set-env name=MY_SHA::$(git rev-parse --short=7 HEAD)
        echo ::set-env name=PULL_NUMBER::$(echo "$GITHUB_REF" | awk -F / '{print $2,$3}' | sed -e 's/ /_/g')
        echo ::set-env name=APP_VERSION_NUM::$(sed -n '/module-version:/{n;p;}' kbase.yml | sed 's/ //g')
        echo ::set-env name=TEST_APP::$(echo ${GITHUB_REPOSITORY}/$(echo $GITHUB_REPOSITORY | awk -F / '{print $2}' | sed -e "s/:refs//")"-dev")
        echo ::set-env name=MY_DEV_APP::$(echo ${GITHUB_REPOSITORY}/$(echo $GITHUB_REPOSITORY | awk -F / '{print $2}' | sed -e "s/:refs//")"-appdev")
        echo ::set-env name=MY_NEXT_APP::$(echo ${GITHUB_REPOSITORY}/$(echo $GITHUB_REPOSITORY | awk -F / '{print $2}' | sed -e "s/:refs//")"-next")
        echo ::set-env name=MY_CI_APP::$(echo ${GITHUB_REPOSITORY}/$(echo $GITHUB_REPOSITORY | awk -F / '{print $2}' | sed -e "s/:refs//")"-ci")
        echo ::set-env name=MY_PROD_APP::$(echo ${GITHUB_REPOSITORY}/$(echo $GITHUB_REPOSITORY | awk -F / '{print $2}' | sed -e "s/:refs//")"-prod")
        echo ::set-env name=MY_USER::$(echo $GITHUB_REPOSITORY | awk -F / '{print $1}' )
        echo ::set-env name=MY_GPR::$(echo $GITHUB_REPOSITORY | awk -F / '{print $2}' )


## Determine if the current image is already tagged for the various environments
## (Mis)uses the :github: v4 GraphQL API
    - name: Check for existing images
      if: github.event.pull_request.merged == false
      run: |
        echo ::set-env name=ISDEV::$(curl -s https://github.com/kbase/narrative-traefiker/packages/341891/versions | grep -c $MY_SHA)
        echo ::set-env name=ISCI::$(curl -s https://github.com/kbase/narrative-traefiker/packages/341898/versions | grep -c $MY_SHA)
        echo ::set-env name=ISNEXT::$(curl -s https://github.com/kbase/narrative-traefiker/packages/341896/versions | grep -c $MY_SHA)


## Confirm variables
    - name: Verify Version and Repo Name
      if: github.event.pull_request.merged == false
      run: |
        echo "Version:" $APP_VERSION_NUM
        echo "Repo:" $GITHUB_REPOSITORY
        echo "Head SHA:" ${{ github.event.pull_request.head.sha }}
        echo "MY_SHA:" $MY_SHA
        echo "Image count dev:" $ISDEV
        echo "Image count next:" $ISNEXT
        echo "Image count CI:" $ISCI
        echo "Image count prod:" $ISPROD
        echo "Appdev Endpoint:" $MY_DEV_APP
        echo "Next Endpoint:" $MY_NEXT_APP
        echo "CI Endpoint:" $MY_CI_APP
        echo "Prod Endpoint:" $MY_PROD_APP
        echo "Versions:" $VERSIONS
        echo "SHA:" $GITHUB_SHA
        echo "REF:" $GITHUB_REF
        echo "HeadRef:" $GITHUB_HEAD_REF
        echo "PR:" $PULL_NUMBER
        echo "User:" $MY_USER
        echo "Package:" $MY_GPR


## Set target Docker image based on new pull request label

    - name: Tag Appdev
      if: contains( github.event.pull_request.labels.*.name, 'appdev') && env.ISDEV < 1 && github.event.pull_request.merged == false
      run: |
        echo "App:" $MY_DEV_APP
        docker login -u ${{ github.actor }} -p ${{ secrets.GITHUB_TOKEN }} docker.pkg.github.com
        docker pull docker.pkg.github.com/$TEST_APP:${{ github.event.pull_request.head.sha }}
        docker tag docker.pkg.github.com/$TEST_APP:${{ github.event.pull_request.head.sha }} docker.pkg.github.com/$MY_DEV_APP:${{ github.event.pull_request.head.sha }}
        docker tag docker.pkg.github.com/$MY_DEV_APP:${{ github.event.pull_request.head.sha }} docker.pkg.github.com/$MY_DEV_APP:${{ github.event.pull_request.number }}
        docker tag docker.pkg.github.com/$MY_DEV_APP:${{ github.event.pull_request.head.sha }} docker.pkg.github.com/$MY_DEV_APP:$GITHUB_HEAD_REF
        docker push docker.pkg.github.com/$MY_DEV_APP:${{ github.event.pull_request.head.sha }}
        docker push docker.pkg.github.com/$MY_DEV_APP:$GITHUB_HEAD_REF
        docker push docker.pkg.github.com/$MY_DEV_APP:${{ github.event.pull_request.number }}

    - name: Tag CI
      if: contains( github.event.pull_request.labels.*.name, 'ci') && env.ISCI < 1 && github.event.pull_request.merged == false
      run: |
        docker login -u ${{ github.actor }} -p ${{ secrets.GITHUB_TOKEN }} docker.pkg.github.com
        docker pull docker.pkg.github.com/$TEST_APP:sha-$MY_SHA
        docker tag docker.pkg.github.com/$TEST_APP:sha-$MY_SHA docker.pkg.github.com/$MY_CI_APP:sha-$MY_SHA
        docker tag docker.pkg.github.com/$MY_CI_APP:sha-$MY_SHA docker.pkg.github.com/$MY_CI_APP:$PULL_NUMBER
        docker tag docker.pkg.github.com/$MY_CI_APP:sha-$MY_SHA docker.pkg.github.com/$MY_CI_APP:$GITHUB_HEAD_REF
        docker push docker.pkg.github.com/$MY_CI_APP:sha-$MY_SHA
        docker push docker.pkg.github.com/$MY_CI_APP:$GITHUB_HEAD_REF
        docker push docker.pkg.github.com/$MY_CI_APP:$PULL_NUMBER

    - name: Tag Next
      if: contains( github.event.pull_request.labels.*.name, 'next') && env.ISNEXT < 1 && github.event.pull_request.merged == false
      run: |
        docker login -u ${{ github.actor }} -p ${{ secrets.GITHUB_TOKEN }} docker.pkg.github.com
        docker pull docker.pkg.github.com/$TEST_APP:sha-$MY_SHA
        docker tag docker.pkg.github.com/$TEST_APP:sha-$MY_SHA docker.pkg.github.com/$MY_NEXT_APP:sha-$MY_SHA
        docker tag docker.pkg.github.com/$MY_NEXT_APP:sha-$MY_SHA docker.pkg.github.com/$MY_NEXT_APP:$PULL_NUMBER
        docker tag docker.pkg.github.com/$MY_NEXT_APP:sha-$MY_SHA docker.pkg.github.com/$MY_NEXT_APP:$GITHUB_HEAD_REF
        docker push docker.pkg.github.com/$MY_NEXT_APP:sha-$MY_SHA
        docker push docker.pkg.github.com/$MY_NEXT_APP:$GITHUB_HEAD_REF
        docker push docker.pkg.github.com/$MY_NEXT_APP:$PULL_NUMBER