---
name: Build & Tag `develop`
on:
  pull_request:
    branches:
      - develop

jobs:
  docker_build:
    runs-on: ubuntu-latest
    steps:

    - name: Check out GitHub Repo
      if: "!contains(github.event.head_commit.message, 'skip ci')"
      with:
        ref: ${{ github.event.pull_request.head.sha }}
      uses: actions/checkout@v2

    - name: Build and Push to Packages
      if: "!contains(github.event.head_commit.message, 'skip ci')"
      env:
        PR: ${{ github.event.pull_request.number }}
        SHA: ${{ github.event.pull_request.head.sha }}
        DOCKER_ACTOR: ${{ github.actor }}
        DOCKER_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        ./.github/workflows/scripts/docker_build.sh
        
